name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: swaekaa
          outputs: |
            snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake"
          add: "snake.svg"
